
export const metadata = {
  title: `Luke's personal site`,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}
        </body>
    </html>
  )
}
